services:
  lestodb:
    build: . 
    image: lestodb:latest
    container_name: lestodb
    
    ports:
      - "2001:2001"
    
    environment:
      - SHARDING_COUNT=36
      - PORT=2001
      - URL=0.0.0.0 
      - FILE_PATH=/app/database/lesto.db 
    volumes:
      - ./data:/app/database
      
    restart: unless-stopped